title: Quid scio? 
description: Less IS more
#show_downloads: true
google_analytics:

# GitHub Pages repository format
repository: quidscio/quidscio.github.io
# Git URL can be specified in a different variable if needed for other purposes
git_url: https://github.com/quidscio/quidscio.github.io.git

theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight

# Note: PAGES_REPO_NWO environment variable is no longer needed with this setup

url: "http://polaris360.com"

# Add a navigation menu
navigation:
  - title: Home
    url: /
  - title: Posts
    url: /posts/
  - title: About
    url: /about/

collections:
  posts:
    output: true
    permalink: /posts/:title/

sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sass-converter
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-theme-midnight  # Add this